# Generated by Django 4.1 on 2023-03-29 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shi_collection_authors', to='main.account')),
                ('shi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shi_collection_shis', to='main.shi')),
            ],
            options={
                'verbose_name': 'ShiCollection',
                'verbose_name_plural': 'ShiCollections',
                'db_table': 'shi_collection',
                'ordering': ['-create_date'],
            },
        ),
    ]
