# Generated by Django 4.1 on 2023-03-29 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shicollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci_collection_authors', to='main.account')),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci_collection_cis', to='main.ci')),
            ],
            options={
                'verbose_name': 'CiCollection',
                'verbose_name_plural': 'CiCollections',
                'db_table': 'ci_collection',
                'ordering': ['-create_date'],
            },
        ),
    ]
